apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: network-composition
  labels:
    guide: crossplane-network
spec:
  compositeTypeRef:
    apiVersion: platform.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
  - step: environment-configs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
          - type: Selector
            selector:
              mode: Single
              matchLabels:
                - key: environment
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.parameters.environment
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: vpc
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: VPC
          spec:
            forProvider:
              cidrBlock: 10.0.0.0/16
              tags:
                managed-by: crossplane
                provisioned-by: backstage-idp
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - type: FromEnvironmentFieldPath
          fromFieldPath: vpcCidr
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.vpcCidr
          toFieldPath: spec.forProvider.cidrBlock
          policy:
            fromFieldPath: Optional
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.vpcId
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: mandatory-tags
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: subnet-a
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            labels:
              managed-by: crossplane
          spec:
            forProvider:
              cidrBlock: 10.0.1.0/24
              availabilityZone: ''
              mapPublicIpOnLaunch: true
              tags:
                managed-by: crossplane
                provisioned-by: backstage-idp
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-a'
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%sa'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - type: FromEnvironmentFieldPath
          fromFieldPath: subnetACidr
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.subnetACidr
          toFieldPath: spec.forProvider.cidrBlock
          policy:
            fromFieldPath: Optional
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.subnetAId
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: metadata.labels[environment]
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: mandatory-tags
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: subnet-b
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            labels:
              managed-by: crossplane
          spec:
            forProvider:
              cidrBlock: 10.0.2.0/24
              availabilityZone: ''
              mapPublicIpOnLaunch: true
              tags:
                managed-by: crossplane
                provisioned-by: backstage-idp
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-b'
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%sb'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - type: FromEnvironmentFieldPath
          fromFieldPath: subnetBCidr
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.subnetBCidr
          toFieldPath: spec.forProvider.cidrBlock
          policy:
            fromFieldPath: Optional
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.subnetBId
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: metadata.labels[environment]
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: mandatory-tags
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: igw
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: InternetGateway
          spec:
            forProvider:
              tags:
                managed-by: crossplane
                provisioned-by: backstage-idp
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-igw'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.internetGatewayId
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: mandatory-tags
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: route-table
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTable
          spec:
            forProvider:
              tags:
                managed-by: crossplane
                provisioned-by: backstage-idp
        patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.routeTableId
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: mandatory-tags
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: route-to-igw
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Route
          spec:
            forProvider:
              destinationCidrBlock: 0.0.0.0/0
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-route-igw'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.gatewayIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-igw'
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: rta-subnet-a
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTableAssociation
          spec:
            forProvider: {}
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rta-a'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.subnetIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-a'
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      - name: rta-subnet-b
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTableAssociation
          spec:
            forProvider: {}
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rta-b'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.subnetIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-b'
        - type: PatchSet
          patchSetName: regional-resource
        - type: PatchSet
          patchSetName: deletion-policy
        - type: PatchSet
          patchSetName: provider-config-ref
      patchSets:
      - name: regional-resource
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
      - name: mandatory-tags
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.tags["environment"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.tags["region"]
      - name: deletion-policy
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.deletionPolicy
          transforms:
          - type: map
            map:
              dev: Delete
              staging: Orphan
      - name: provider-config-ref
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.providerConfigRef.name
          transforms:
          - type: map
            map:
              dev: aws-dev
              staging: aws-staging
  - step: go-templating
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ if .observed.composite.resource.spec.parameters.enableNatGateway }}
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: EIP
          metadata:
            name: {{ .observed.composite.resource.metadata.name }}-nat-eip
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: nat-eip
          spec:
            providerConfigRef:
              name: {{ if eq .observed.composite.resource.spec.parameters.environment "dev" }}aws-dev{{ else }}aws-staging{{ end }}
            deletionPolicy: {{ if eq .observed.composite.resource.spec.parameters.environment "dev" }}Delete{{ else }}Orphan{{ end }}
            forProvider:
              domain: vpc
              region: {{ .observed.composite.resource.spec.parameters.region }}
              tags:
                environment: {{ .observed.composite.resource.spec.parameters.environment }}
                managed-by: crossplane
                provisioned-by: backstage-idp
                region: {{ .observed.composite.resource.spec.parameters.region }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: NATGateway
          metadata:
            name: {{ .observed.composite.resource.metadata.name }}-nat-gw
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: nat-gw
          spec:
            providerConfigRef:
              name: {{ if eq .observed.composite.resource.spec.parameters.environment "dev" }}aws-dev{{ else }}aws-staging{{ end }}
            deletionPolicy: {{ if eq .observed.composite.resource.spec.parameters.environment "dev" }}Delete{{ else }}Orphan{{ end }}
            forProvider:
              allocationIdRef:
                name: {{ .observed.composite.resource.metadata.name }}-nat-eip
              subnetIdRef:
                name: {{ .observed.composite.resource.metadata.name }}-subnet-a
              region: {{ .observed.composite.resource.spec.parameters.region }}
              tags:
                environment: {{ .observed.composite.resource.spec.parameters.environment }}
                managed-by: crossplane
                provisioned-by: backstage-idp
                region: {{ .observed.composite.resource.spec.parameters.region }}
          {{ end }}
