# Provider manifest for AWS EKS
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v1.13.0
