# Provider manifest for AWS EC2
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v0.47.0
