apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions
  namespace: argocd
spec:
  project: idp-platform

  source:
    repoURL: https://github.com/nimishmehta8779/idp-gitops.git
    targetRevision: main
    path: infrastructure/crossplane/eks
    directory:
      recurse: false
      exclude: 'claim-example.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
