apiVersion: platform.io/v1alpha1
kind: EKSCluster
metadata:
  name: ${{ values.clusterName }}
  namespace: clusters
spec:
  parameters:
    clusterName: ${{ values.clusterName }}
    region: ${{ values.awsRegion }}
    nodeInstanceType: ${{ values.instanceType }}
    nodeCount: ${{ values.nodeCount }}
    kubernetesVersion: "${{ values.kubernetesVersion }}"
    environment: ${{ values.environment }}
    teamName: ${{ values.teamName }}
  writeConnectionSecretToRef:
    name: ${{ values.clusterName }}-kubeconfig
