apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.clusterName }}
  title: ${{ values.clusterName }}
  tags:
    - eks
    - aws
    - ${{ values.environment }}
  links:
    - url: https://github.com/nimishmehta8779/${{ values.teamName }}-infra/blob/main/eks/${{ values.clusterName }}.yaml
      title: GitOps claim
      icon: github
    - url: http://localhost:8080/applications/${{ values.teamName }}-eks-clusters
      title: ArgoCD sync status
      icon: dashboard
  annotations:
    backstage.io/source-location: url:https://github.com/nimishmehta8779/${{ values.teamName }}-infra/blob/main/eks/${{ values.clusterName }}-catalog.yaml
    github.com/project-slug: nimishmehta8779/${{ values.teamName }}-infra
    idp.platform.io/cluster-status: provisioning
    idp.platform.io/aws-region: ${{ values.awsRegion }}
    idp.platform.io/cluster-version: "${{ values.kubernetesVersion }}"
    idp.platform.io/node-count: "${{ values.nodeCount }}"
    idp.platform.io/instance-type: ${{ values.instanceType }}
    idp.platform.io/environment: ${{ values.environment }}
    idp.platform.io/created-by: ${{ values.teamName }}
    backstage.io/kubernetes-id: ${{ values.clusterName }}
    backstage.io/kubernetes-namespace: {% if values.environment == 'dev' %}clusters-dev{% else %}clusters-staging{% endif %}
spec:
  type: kubernetes-cluster
  lifecycle: experimental
  owner: group:default/${{ values.teamName }}
  system: eks-provisioning
