apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crossplane-eks-composition
  namespace: default
  description: EKS Cluster Provisioner Composition Component
  annotations:
    backstage.io/source-location: url:https://github.com/company/idp-platform
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  system: system:default/eks-provisioning
  providesApis:
    - api:default/eks-cluster-claim-api
    - api:default/crossplane-xrd-api
