apiVersion: platform.io/v1alpha1
kind: ThreeTierApp
metadata:
  name: ${{ values.appName }}-${{ values.environment }}
  namespace: {% if values.environment == 'dev' %}apps-dev{% else %}apps-staging{% endif %}
  labels:
    team: ${{ values.teamName }}
    environment: ${{ values.environment }}
    pattern: three-tier-web
    managed-by: crossplane
    provisioned-by: backstage-idp
    cost-center: ${{ values.costCenter }}
    backstage.io/kubernetes-id: ${{ values.appName }}-${{ values.environment }}
  annotations:
    idp.platform.io/app-name: ${{ values.appName }}
    idp.platform.io/environment: ${{ values.environment }}
    idp.platform.io/aws-region: ${{ values.region }}
    idp.platform.io/created-by: ${{ values.teamName }}
    idp.platform.io/network-ref: ${{ values.networkRef }}
    idp.platform.io/cost-acknowledged: "true"
    backstage.io/kubernetes-id: ${{ values.appName }}-${{ values.environment }}
    backstage.io/kubernetes-namespace: {% if values.environment == 'dev' %}apps-dev{% else %}apps-staging{% endif %}
spec:
  parameters:
    appName: ${{ values.appName }}
    teamName: ${{ values.teamName }}
    environment: ${{ values.environment }}
    region: ${{ values.region }}
    costCenter: ${{ values.costCenter }}
    networkRef: ${{ values.networkRef }}
    dbInstanceClass: ${{ values.dbInstanceClass }}
    ecsTaskCpu: ${{ values.ecsTaskCpu }}
    ecsTaskMemory: ${{ values.ecsTaskMemory }}
    desiredCount: ${{ values.desiredCount }}
    containerPort: ${{ values.containerPort }}
    healthCheckPath: ${{ values.healthCheckPath }}
    enableWaf: ${{ values.enableWaf }}
    enableRoute53: ${{ values.enableRoute53 }}
    {% if values.domainName %}domainName: ${{ values.domainName }}{% endif %}
  compositionRef:
    name: three-tier-web
  writeConnectionSecretToRef:
    name: ${{ values.appName }}-${{ values.environment }}-connection
    namespace: {% if values.environment == 'dev' %}apps-dev{% else %}apps-staging{% endif %}
