apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: developer-platform
  namespace: default
  description: The Developer Platform Domain
spec:
  owner: group:default/platform-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp-core
  namespace: default
  description: Core Backstage IDP Portal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:default/platform-team
  domain: developer-platform

