apiVersion: platform.io/v1alpha1
kind: EKSCluster
metadata:
  name: alpha-test
  namespace: clusters-dev
  labels:
    team: team-alpha
    environment: dev
    managed-by: crossplane
  annotations:
    idp.platform.io/cost-acknowledged: "true"
spec:
  parameters:
    clusterName: alpha-test
    region: us-east-1
    nodeInstanceType: t3.medium
    nodeCount: 2
    kubernetesVersion: "1.34"
    environment: dev
    teamName: team-alpha
    networkRef: dev-network
  writeConnectionSecretToRef:
    name: alpha-test-kubeconfig
    namespace: clusters-dev
