apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eks-cluster
  labels:
    guide: crossplane-eks
spec:
  compositeTypeRef:
    apiVersion: platform.io/v1alpha1
    kind: XEKSCluster
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: vpc
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: VPC
          spec:
            forProvider:
              cidrBlock: 10.0.0.0/16
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
        - fromFieldPath: spec.parameters.teamName
          toFieldPath: spec.forProvider.tags["team"]
        - fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.tags["environment"]
      - name: subnet-a
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          spec:
            forProvider:
              cidrBlock: 10.0.1.0/24
              availabilityZone: ''
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-a'
        - fromFieldPath: spec.parameters.teamName
          toFieldPath: spec.forProvider.tags["team"]
        - fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.tags["environment"]
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%sa'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
      - name: subnet-b
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          spec:
            forProvider:
              cidrBlock: 10.0.2.0/24
              availabilityZone: ''
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-b'
        - fromFieldPath: spec.parameters.teamName
          toFieldPath: spec.forProvider.tags["team"]
        - fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.tags["environment"]
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.availabilityZone
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%sb'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
      - name: igw
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: InternetGateway
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-igw'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
      - name: route-table
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTable
          spec:
            forProvider: {}
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-vpc'
      - name: eks-cluster
        base:
          apiVersion: eks.aws.upbound.io/v1beta1
          kind: Cluster
          spec:
            forProvider:
              version: '1.34'
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s'
        - fromFieldPath: spec.parameters.kubernetesVersion
          toFieldPath: spec.forProvider.version
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.roleArn
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcConfig[0].subnetIdRefs[0].name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-a'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.vpcConfig[0].subnetIdRefs[1].name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-b'
      - name: nodegroup-role
        base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          spec:
            forProvider:
              assumeRolePolicy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\"\
                : [{\n    \"Effect\": \"Allow\",\n    \"Principal\": {\"Service\"\
                : \"ec2.amazonaws.com\"},\n    \"Action\": \"sts:AssumeRole\"\n  }]\n\
                }\n"
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-node-role'
        - fromFieldPath: spec.parameters.teamName
          toFieldPath: spec.forProvider.tags["team"]
        - fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.tags["environment"]
      - name: node-group
        base:
          apiVersion: eks.aws.upbound.io/v1beta1
          kind: NodeGroup
          spec:
            forProvider:
              instanceTypes: []
              scalingConfig:
              - desiredSize: 2
                minSize: 1
                maxSize: 10
        patches:
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-node-group'
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.clusterName
        - fromFieldPath: spec.parameters.nodeInstanceType
          toFieldPath: spec.forProvider.instanceTypes[0]
        - fromFieldPath: spec.parameters.nodeCount
          toFieldPath: spec.forProvider.scalingConfig[0].desiredSize
        - fromFieldPath: spec.parameters.nodeCount
          toFieldPath: spec.forProvider.scalingConfig[0].minSize
        - fromFieldPath: spec.parameters.nodeCount
          toFieldPath: spec.forProvider.scalingConfig[0].maxSize
        - fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.nodeRoleArnRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-node-role'
      - name: route-to-igw
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Route
          spec:
            forProvider:
              destinationCidrBlock: 0.0.0.0/0
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-route-igw'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.gatewayIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-igw'
      - name: rta-subnet-a
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTableAssociation
          spec:
            forProvider: {}
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rta-a'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.subnetIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-a'
      - name: rta-subnet-b
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: RouteTableAssociation
          spec:
            forProvider: {}
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rta-b'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.routeTableIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-rt'
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.forProvider.subnetIdRef.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-subnet-b'
