apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-eks-clusters
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - team: team-yamma
            repo: https://github.com/nimishmehta8779/team-yamma-infra.git
          - team: team-alpha
            repo: team-alpha-infra
          - team: team-beta
            repo: team-beta-infra
          - team: team-gamma
            repo: team-gamma-infra

  template:
    metadata:
      name: '{{team}}-eks-clusters'
      labels:
        team: '{{team}}'
        managed-by: argocd-applicationset
    spec:
      project: idp-platform-dev
      source:
        repoURL: 'https://github.com/nimishmehta8779/{{repo}}'
        targetRevision: main
        path: eks
        directory:
          recurse: true
          include: '*.yaml'
          exclude: '{.gitkeep,*-catalog.yaml}'
      destination:
        server: https://kubernetes.default.svc
        namespace: clusters-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      ignoreDifferences:
        - group: platform.io
          kind: XEKSCluster
          jsonPointers:
            - /status
            - /metadata/annotations/crossplane.io
