apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - repo: team-alpha-infra
            team: team-alpha
          - repo: team-beta-infra
            team: team-beta
          - repo: team-gamma-infra
            team: team-gamma
          - repo: team-yamma-infra
            team: team-yamma

  template:
    metadata:
      name: '{{team}}-apps'
      labels:
        team: '{{team}}'
        managed-by: argocd-applicationset
    spec:
      project: idp-platform-dev
      source:
        repoURL: 'https://github.com/nimishmehta8779/{{repo}}'
        targetRevision: main
        path: apps
        directory:
          recurse: true
          include: '*.yaml'
          exclude: '{.gitkeep,**/catalog-info.yaml,**/*-catalog.yaml}'
      destination:
        server: https://kubernetes.default.svc
        namespace: apps-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: platform.io
          kind: ThreeTierApp
          jsonPointers:
            - /status
            - /metadata/annotations/crossplane.io
