apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-infra-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - team: team-beta
            repo: https://github.com/nimishmehta8779/team-beta-infra.git
  template:
    metadata:
      name: '{{team}}-infra'
    spec:
      project: idp-platform
      source:
        repoURL: '{{repo}}'
        targetRevision: main
        path: .
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: clusters
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
