apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-eks-clusters-staging
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - team: team-alpha
            repo: team-alpha-infra
          - team: team-beta
            repo: team-beta-infra
          - team: team-gamma
            repo: team-gamma-infra

  template:
    metadata:
      name: '{{team}}-eks-clusters-staging'
      labels:
        team: '{{team}}'
        managed-by: argocd-applicationset
    spec:
      project: idp-platform-staging
      source:
        repoURL: 'https://github.com/nimishmehta8779/{{repo}}'
        targetRevision: main
        path: eks
        directory:
          recurse: true
          include: '*-staging-*.yaml'
          exclude: '.gitkeep'
      destination:
        server: https://kubernetes.default.svc
        namespace: clusters-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      ignoreDifferences:
        - group: platform.io
          kind: XEKSCluster
          jsonPointers:
            - /status
            - /metadata/annotations/crossplane.io
