apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-eks-clusters-staging
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          organization: nimishmehta8779
          tokenRef:
            secretName: org-github-creds
            key: password
        filters:
          - repositoryMatch: '^team-.*-infra$'

  template:
    metadata:
      name: '{{repository | replace "-infra" ""}}-eks-clusters-staging'
      labels:
        team: '{{repository | replace "-infra" ""}}'
        managed-by: argocd-applicationset
    spec:
      project: idp-platform-staging
      source:
        repoURL: '{{url}}'
        targetRevision: main
        path: eks
        directory:
          recurse: true
          include: '*-staging-*.yaml'
          exclude: '.gitkeep'
      destination:
        server: https://kubernetes.default.svc
        namespace: clusters-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: platform.io
          kind: XEKSCluster
          jsonPointers:
            - /status
            - /metadata/annotations/crossplane.io
