apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
  namespace: default
  description: Platform Engineer
  annotations:
    github.com/user-login: nimishmehta8779
spec:
  profile:
    displayName: Alice Smith
    email: alice@example.com
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob
  namespace: default
  description: Platform Engineer
  annotations:
    github.com/user-login: bob-github
spec:
  profile:
    displayName: Bob Jones
    email: bob@example.com
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: charlie
  namespace: default
  description: Alpha Developer
  annotations:
    github.com/user-login: charlie-github
spec:
  profile:
    displayName: Charlie Brown
    email: charlie@example.com
  memberOf: [team-alpha]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: david
  namespace: default
  description: Alpha Developer
  annotations:
    github.com/user-login: david-github
spec:
  profile:
    displayName: David Miller
    email: david@example.com
  memberOf: [team-alpha]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eve
  namespace: default
  description: Beta Developer
  annotations:
    github.com/user-login: eve-github
spec:
  profile:
    displayName: Eve Davis
    email: eve@example.com
  memberOf: [team-beta]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank
  namespace: default
  description: Beta Developer
  annotations:
    github.com/user-login: frank-github
spec:
  profile:
    displayName: Frank Wilson
    email: frank@example.com
  memberOf: [team-beta]
