apiVersion: v1
kind: Secret
metadata:
  name: idp-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nimishmehta8779/idp-gitops.git
  password: GITHUB_TOKEN_PLACEHOLDER
  username: nimishmehta8779
