apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-gamma
  title: Gamma Team
  annotations:
    backstage.io/source-location: url:https://github.com/nimishmehta8779/team-gamma-infra
    idp.platform.io/cost-center: "CC-GAMMA"
    idp.platform.io/primary-region: "us-east-1"
    idp.platform.io/onboarded-at: "${{ now() }}"
spec:
  type: team
  profile:
    displayName: Gamma Team
    email: team-gamma@platform.io
  parent: engineering
  members:
    - nimishmehta8779
