apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-yamma
  title: Yamma Dev Team
  annotations:
    backstage.io/source-location: url:https://github.com/nimishmehta8779/team-yamma-infra
    idp.platform.io/cost-center: "401"
    idp.platform.io/primary-region: "us-east-1"
    idp.platform.io/onboarded-at: "${{ now() }}"
spec:
  type: team
  profile:
    displayName: Yamma Dev Team
    email: teama.yamma@gmail.com
  parent: engineering
  members:
    - nimishmehta8779
