apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-alpha
  title: Alpha Team
  annotations:
    backstage.io/source-location: url:https://github.com/nimishmehta8779/team-alpha-infra
    idp.platform.io/cost-center: "CC-1234"
    idp.platform.io/primary-region: "us-east-1"
    idp.platform.io/onboarded-at: "${{ now() }}"
spec:
  type: team
  profile:
    displayName: Alpha Team
    email: alpha@example.com
  parent: engineering
  members:
    - {{ member | trim }}
