apiVersion: platform.io/v1alpha1
kind: EKSCluster
metadata:
  name: alpha-test
  namespace: clusters
spec:
  parameters:
    clusterName: alpha-test
    region: us-east-1
    nodeInstanceType: t3.medium
    nodeCount: 2
    kubernetesVersion: "1.29"
    environment: dev
    teamName: team-alpha
  writeConnectionSecretToRef:
    name: alpha-test-kubeconfig
    namespace: clusters
