apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: alpha-dev-general-01
  description: EKS cluster requested by team-alpha
  tags:
    - eks
    - aws
    - dev
  links:
    - url: https://github.com/nimishmehta8779/idp-gitops/blob/main/gitops/cluster-claims/team-alpha/alpha-dev-general-01.yaml
      title: GitOps claim
      icon: github
    - url: http://localhost:8080/applications/cluster-claims
      title: ArgoCD sync status
      icon: dashboard
  annotations:
    idp.platform.io/cluster-status: provisioning
    idp.platform.io/aws-region: us-east-1
    idp.platform.io/cluster-version: "1.34"
    idp.platform.io/node-count: "2"
    idp.platform.io/instance-type: t3.medium
    idp.platform.io/environment: dev
    idp.platform.io/created-by: team-alpha
    idp.platform.io/monthly-cost-estimate: "${{ parameters.instanceType === 't3.medium' ? 72 + (parameters.nodeCount * 30) : parameters.instanceType === 't3.large' ? 72 + (parameters.nodeCount * 60) : 72 + (parameters.nodeCount * 70) }}"
    backstage.io/kubernetes-id: alpha-dev-general-01
    backstage.io/kubernetes-namespace: clusters
spec:
  type: kubernetes-cluster
  owner: group:default/team-alpha
  system: eks-provisioning
